TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE += sioc-sim-B084-158.archive

include $(TOP)/configure/RULES
-include $(TOP)/configure/RULES.archive
#----------------------------------------
#  ADD RULES AFTER THIS LINE
